export const ADD_TO_CART = 'ADD_TO_CART'
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS'
export const ADD_TO_CART_FAILED = 'ADD_TO_CART_FAILED'

export const USER_CART = 'USER_CART'
export const USER_CART_SUCCESS = 'USER_CART_SUCCESS'
export const USER_CART_FAILED = 'USER_CART_FAILED'

export const GET_USER_CART = 'GET_USER_CART'
export const GET_USER_CART_SUCCESS = 'GET_USER_CART_SUCCESS'
export const GET_USER_CART_FAILED = 'GET_USER_CART_FAILED'

export const EMPTY_CART = 'EMPTY_CART'
export const EMPTY_CART_SUCCESS = 'EMPTY_CART_SUCCESS'
export const EMPTY_CART_FAILED = 'EMPTY_CART_FAILED'

export const ADD_ADDRESS_CART = 'ADD_ADDRESS_CART'
export const ADD_ADDRESS_CART_SUCCESS = 'ADD_ADDRESS_CART_SUCCESS'
export const ADD_ADDRESS_CART_FAILED = 'ADD_ADDRESS_CART_FAILED'

export const APPLY_COUPON_CART = 'APPLY_COUPON_CART'
export const APPLY_COUPON_CART_SUCCESS = 'APPLY_COUPON_CART_SUCCESS'
export const APPLY_COUPON_CART_FAILED = 'APPLY_COUPON_CART_FAILED'
