const PATHS = {
  HOME: '/',
  REGISTER: 'register',
  LOGIN: 'login',
  COMPLETE: 'complete',
  FORGOT: 'forgot',
  AUTH: 'auth',
  PASSWORD: 'password',
  HISTORY: 'history',
  USER: 'user',
  WISHLIST: 'wishlist',
  ADMIN: 'admin',
  DASHBOARD: 'dashboard',
  CATEGORY: 'category',
  LIST: 'list',
  PRODUCT: 'product',
  LIST_PRODUCTS: 'list-products',
  SUB_CATEGORY: 'sub-category',
  COUPON: 'coupon',
  SUBS: 'subs',
  TOTAL: 'total',
  RELATED: 'related',
  CART: 'cart',
  CHECKOUT: 'check-out',
  ADDRESS: 'address',
  PAYMENT: 'payment',
  ORDER: 'order',
  ORDERS: 'orders',
}

export default PATHS
