export const LOADING_POST = 'LOADING_POST'
export const CREATE_POST = 'CREATE_POST'
export const UPDATE_POST = 'CREATE_POST'
export const GET_POSTS = 'GET_POSTS'
export const STATUS_POST = 'STATUS_POST'
