// LOGIN USER
export const LOGGIN_IN_USER = 'LOGGIN_IN_USER'
export const LOGGIN_IN_USER_SUCCESS = 'LOGGIN_IN_USER_SUCCESS'
export const LOGGIN_IN_USER_FAILED = 'LOGGIN_IN_USER_FAILED'

export const LOGOUT_IN_USER = 'LOGOUT_IN_USER'
